In [1]:
%load_ext lab_black
%config Completer.use_jedi = False
import pandas as pd
from Grid_Tuning_arithmetic import grid_trading, speedy_grid_trading
from tqdm import tqdm
import time

In [6]:
%%time

# FILENAME = "Mild_Fluctuate_data.csv"
FILENAME = "Increasing_Data.csv"
data = pd.read_csv(FILENAME)
# optimization_arithmetic=[]
# for interval_for_bounds in tqdm(range(5,20)):
#     for sd in range(2,5):
#         records_df, final_profit = speedy_grid_trading(
#             data, INTERVAL_FOR_BOUNDS=interval_for_bounds * 24 * 60, SD_PARAMETER=sd,
#         )
#         optimization_arithmetic.append([final_profit, "", interval_for_bounds, sd])

Wall time: 81 ms


In [18]:
# optimization=[]
# for interval_for_rsv in tqdm(range(10, 60)):
#     for interval_for_bounds in range(2, 20):
#         for sd_parameter in range(2,5):
#             records_df, final_profit = grid_trading(
#                 data, INTERVALS_FOR_RSV=interval_for_rsv, INTERVAL_FOR_BOUNDS=interval_for_bounds * 24 * 60, SD_PARAMETER=sd_parameter,
#             )
#             optimization.append([final_profit, interval_for_rsv, interval_for_bounds, sd_parameter])
#             print(time.ctime())

In [7]:
optimization_df = pd.DataFrame(
    optimization_arithmetic,
    columns=["FinalProfit", "IntervalForRSV", "IntervalForBounds", "SDParameter",],
)

In [17]:
optimization_df.to_excel("Training_ArithmeticSequence.xlsx")
# optimization_df = pd.read_excel("Training.xlsx")
optimization_df

FinalProfit IntervalForRSV  IntervalForBounds  SDParameter
0        179241                                 5            2
1        214681                                 5            3
2        151395                                 5            4
3        172191                                 6            2
4        148440                                 6            3
5        157398                                 6            4
6        166943                                 7            2
7        197137                                 7            3
8        162886                                 7            4
9        193953                                 8            2
10       175958                                 8            3
11       194118                                 8            4
12       181445                                 9            2
13       184765                                 9            3
14       206426                                 9            4
15       179104                                10            2
16       170334                                10            3
17       210745                                10            4
18       167599                                11            2
19       165011                                11            3
20       174586                                11            4
21       159548                                12            2
22       167526                                12            3
23       166301                                12            4
24       170931                                13            2
25       171919                                13            3
26       177751                                13            4
27       175287                                14            2
28       171962                                14            3
29       185855                                14            4
30       164362                                15            2
31       165966                                15            3
32       180692                                15            4
33       205718                                16            2
34       159710                                16            3
35       204924                                16            4
36       204404                                17            2
37       154164                                17            3
38       197041                                17            4
39       159972                                18            2
40       159778                                18            3
41       208307                                18            4
42       146214                                19            2
43       171906                                19            3
44       184480                                19            4

In [9]:
df = optimization_df[
    optimization_df["FinalProfit"] == optimization_df["FinalProfit"].max()
]
SDParameter = df["SDParameter"].unique()
IntervalForBounds = df["IntervalForBounds"].unique()
IntervalForRSV = df["IntervalForRSV"].unique()
FinalProfit = df["FinalProfit"].unique()

In [10]:
SDParameter

array([3], dtype=int64)

In [11]:
IntervalForBounds

array([5], dtype=int64)

In [12]:
IntervalForRSV

array([''], dtype=object)

In [13]:
FinalProfit

array([214681], dtype=int64)

In [7]:
%%time
from Grid_Tuning_arithmetic import grid_trading, speedy_grid_trading

records_df, final_profit = speedy_grid_trading(
    data, INTERVAL_FOR_BOUNDS=5 * 24 * 60, SD_PARAMETER=3,
)
records_df["Hour"] = pd.to_datetime(records_df["Hour"])
records_df

Wall time: 2.54 s


Action  Price    n    Cash  Profit    LowerBound    UpperBound  \
0    Buying  59266  1.0   40734  -59266  53819.309279  60652.158213   
1   Selling  59802  0.0  100536     536  55136.002652  60449.830834   
2    Buying  60339  1.0   40196  -59804  55136.470914  60450.535780   
3   Selling  60938  0.0  101134    1134  55705.857387  61418.803035   
4    Buying  61332  1.0   39803  -60197  55705.548868  61420.861360   
5   Selling  62416  0.0  102219    2219  57120.294102  62519.110026   
6    Buying  63749  1.0   38470  -61530  57233.218109  63769.222377   
7    Buying  59266  1.0   40734  -59266  52111.097045  62360.370447   
8    Buying  59266  1.0   40734  -59266  52111.097045  62360.370447   
9   Selling  59838  0.0  100572     572  55309.682613  60311.516373   
10   Buying  60711  1.0   39861  -60139  55073.193711  60711.379992   
11  Selling  61656  0.0  101517    1517  55908.555581  62729.117060   
12   Buying  62499  1.0   39018  -60982  55908.625684  62730.451166   
13  Selling  63321  0.0  102339    2339  55871.771271  63504.155973   
14   Buying  63566  1.0   38773  -61227  55845.928298  63578.385071   
15   Buying  37516  2.0   24968  -75032  33104.869723  40377.288202   
16  Selling  38439  0.0  101846    1846  30333.593039  39175.182317   
17   Buying  38780  2.0   24286  -75714  30332.171417  39177.823670   
18  Selling  39799  0.0  103884    3884  31465.114864  41555.518566   
19   Buying  40177  2.0   23530  -76470  31465.118753  41557.130597   
20  Selling  40834  0.0  105197    5197  35135.708631  41461.653532   
21   Buying  41086  2.0   23024  -76976  35135.979691  41462.702295   
22  Selling  42686  0.0  108395    8395  34393.776243  42689.416043   
23   Buying  43009  2.0   22377  -77623  34227.077781  43020.738377   
24  Selling  45548  0.0  113473   13473  32683.088869  45587.742925   
25   Buying  47457  2.0   18559  -81441  31562.455095  47517.195336   
26  Selling  48091  0.0  114742   14742  43687.871473  49796.922677   
27   Buying  48714  2.0   17314  -82686  43687.569435  49797.797998   
28  Selling  49422  0.0  116159   16159  43477.580932  50224.015971   

           Grid                Hour  
0    683.284893 2021-03-19 23:59:00  
1    531.382818 2021-02-04 10:34:00  
2    531.406487 2021-02-04 10:35:00  
3    571.294565 2021-12-04 15:32:00  
4    571.531249 2021-12-04 15:34:00  
5    539.881592 2021-04-14 02:54:00  
6    653.600427 2021-04-14 17:24:00  
7   1024.927340 2021-03-19 23:59:00  
8   1024.927340 2021-03-19 23:59:00  
9    500.183376 2021-10-04 12:18:00  
10   563.818628 2021-10-04 15:03:00  
11   682.056148 2021-04-13 16:15:00  
12   682.182548 2021-04-13 16:16:00  
13   763.238470 2021-04-14 00:01:00  
14   773.245677 2021-04-14 00:32:00  
15   727.241848 2021-01-19 23:59:00  
16   884.158928 2021-04-02 16:23:00  
17   884.565225 2021-04-02 16:24:00  
18  1009.040370 2021-06-02 18:57:00  
19  1009.201184 2021-06-02 18:58:00  
20   632.594490 2021-08-02 20:48:00  
21   632.672260 2021-08-02 20:49:00  
22   829.563980 2021-09-02 01:05:00  
23   879.366060 2021-09-02 02:44:00  
24  1290.465406 2021-09-02 10:55:00  
25  1595.474024 2021-09-02 16:15:00  
26   610.905120 2021-02-14 13:47:00  
27   611.022856 2021-02-14 13:48:00  
28   674.643504 2021-02-14 20:16:00

In [8]:
import numpy as np

# records_df = records_df.sort_values(by="Hour", ascending=True)
records_df["TransactionInterval"] = records_df["Hour"].diff()
records_df = records_df.dropna()
records_df.loc[:, "TransactionInterval"] = records_df["TransactionInterval"].apply(
    lambda x: x.seconds
)
records_df

C:\Users\bizjun\Anaconda3\envs\AlgoTrading\lib\site-packages\pandas\core\indexing.py:1676: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)


Action  Price    n    Cash  Profit    LowerBound    UpperBound  \
1   Selling  59802  0.0  100536     536  55136.002652  60449.830834   
2    Buying  60339  1.0   40196  -59804  55136.470914  60450.535780   
3   Selling  60938  0.0  101134    1134  55705.857387  61418.803035   
4    Buying  61332  1.0   39803  -60197  55705.548868  61420.861360   
5   Selling  62416  0.0  102219    2219  57120.294102  62519.110026   
6    Buying  63749  1.0   38470  -61530  57233.218109  63769.222377   
7    Buying  59266  1.0   40734  -59266  52111.097045  62360.370447   
8    Buying  59266  1.0   40734  -59266  52111.097045  62360.370447   
9   Selling  59838  0.0  100572     572  55309.682613  60311.516373   
10   Buying  60711  1.0   39861  -60139  55073.193711  60711.379992   
11  Selling  61656  0.0  101517    1517  55908.555581  62729.117060   
12   Buying  62499  1.0   39018  -60982  55908.625684  62730.451166   
13  Selling  63321  0.0  102339    2339  55871.771271  63504.155973   
14   Buying  63566  1.0   38773  -61227  55845.928298  63578.385071   
15   Buying  37516  2.0   24968  -75032  33104.869723  40377.288202   
16  Selling  38439  0.0  101846    1846  30333.593039  39175.182317   
17   Buying  38780  2.0   24286  -75714  30332.171417  39177.823670   
18  Selling  39799  0.0  103884    3884  31465.114864  41555.518566   
19   Buying  40177  2.0   23530  -76470  31465.118753  41557.130597   
20  Selling  40834  0.0  105197    5197  35135.708631  41461.653532   
21   Buying  41086  2.0   23024  -76976  35135.979691  41462.702295   
22  Selling  42686  0.0  108395    8395  34393.776243  42689.416043   
23   Buying  43009  2.0   22377  -77623  34227.077781  43020.738377   
24  Selling  45548  0.0  113473   13473  32683.088869  45587.742925   
25   Buying  47457  2.0   18559  -81441  31562.455095  47517.195336   
26  Selling  48091  0.0  114742   14742  43687.871473  49796.922677   
27   Buying  48714  2.0   17314  -82686  43687.569435  49797.797998   
28  Selling  49422  0.0  116159   16159  43477.580932  50224.015971   

           Grid                Hour  TransactionInterval  
1    531.382818 2021-02-04 10:34:00                38100  
2    531.406487 2021-02-04 10:35:00                   60  
3    571.294565 2021-12-04 15:32:00                17820  
4    571.531249 2021-12-04 15:34:00                  120  
5    539.881592 2021-04-14 02:54:00                40800  
6    653.600427 2021-04-14 17:24:00                52200  
7   1024.927340 2021-03-19 23:59:00                23700  
8   1024.927340 2021-03-19 23:59:00                    0  
9    500.183376 2021-10-04 12:18:00                44340  
10   563.818628 2021-10-04 15:03:00                 9900  
11   682.056148 2021-04-13 16:15:00                 4320  
12   682.182548 2021-04-13 16:16:00                   60  
13   763.238470 2021-04-14 00:01:00                27900  
14   773.245677 2021-04-14 00:32:00                 1860  
15   727.241848 2021-01-19 23:59:00                84420  
16   884.158928 2021-04-02 16:23:00                59040  
17   884.565225 2021-04-02 16:24:00                   60  
18  1009.040370 2021-06-02 18:57:00                 9180  
19  1009.201184 2021-06-02 18:58:00                   60  
20   632.594490 2021-08-02 20:48:00                 6600  
21   632.672260 2021-08-02 20:49:00                   60  
22   829.563980 2021-09-02 01:05:00                15360  
23   879.366060 2021-09-02 02:44:00                 5940  
24  1290.465406 2021-09-02 10:55:00                29460  
25  1595.474024 2021-09-02 16:15:00                19200  
26   610.905120 2021-02-14 13:47:00                77520  
27   611.022856 2021-02-14 13:48:00                   60  
28   674.643504 2021-02-14 20:16:00                23280

In [18]:
# records_df.to_excel("TransactionHistory_ArithmeticSequence.xlsx")