In [1]:
%load_ext lab_black
%config Completer.use_jedi = False
import pandas as pd
from Grid_Tuning_geometric import grid_trading, speedy_grid_trading
from tqdm import tqdm
import time

In [7]:
%%time

# FILENAME = "Mild_Fluctuate_data.csv"
FILENAME = "Increasing_Data.csv"
data = pd.read_csv(FILENAME)
optimization=[]
# for interval_for_bounds in tqdm(range(5,20)):
#     for sd in range(2,5):
#         records_df, final_profit = speedy_grid_trading(
#             data, INTERVAL_FOR_BOUNDS=interval_for_bounds * 24 * 60, SD_PARAMETER=sd,
#         )
#         optimization.append([final_profit, "", interval_for_bounds, sd])

Wall time: 67 ms


In [4]:
# optimization=[]
# for interval_for_rsv in tqdm(range(10, 60)):
#     for interval_for_bounds in range(2, 20):
#         for sd_parameter in range(2,5):
#             records_df, final_profit = grid_trading(
#                 data, INTERVALS_FOR_RSV=interval_for_rsv, INTERVAL_FOR_BOUNDS=interval_for_bounds * 24 * 60, SD_PARAMETER=sd_parameter,
#             )
#             optimization.append([final_profit, interval_for_rsv, interval_for_bounds, sd_parameter])
#             print(time.ctime())

In [4]:
optimization_df = pd.DataFrame(
    optimization,
    columns=["FinalProfit", "IntervalForRSV", "IntervalForBounds", "SDParameter",],
)

In [5]:
# optimization_df.to_excel("Geometric_Sequence_Training_Parameters.xlsx")
# optimization_df = pd.read_excel("Training.xlsx")
optimization_df

FinalProfit IntervalForRSV  IntervalForBounds  SDParameter
0        146083                                 5            2
1        152521                                 5            3
2        113419                                 5            4
3        129581                                 6            2
4        120412                                 6            3
5        105766                                 6            4
6        134226                                 7            2
7        124318                                 7            3
8        111756                                 7            4
9        128901                                 8            2
10       111604                                 8            3
11       114050                                 8            4
12       134532                                 9            2
13       121695                                 9            3
14       120476                                 9            4
15       125333                                10            2
16       114289                                10            3
17       126836                                10            4
18       105352                                11            2
19       110367                                11            3
20       121966                                11            4
21        98945                                12            2
22       101481                                12            3
23       104411                                12            4
24       108350                                13            2
25       106021                                13            3
26       112721                                13            4
27       115603                                14            2
28       109425                                14            3
29       127460                                14            4
30       175860                                15            2
31       111953                                15            3
32       112201                                15            4
33       135392                                16            2
34        98963                                16            3
35       131530                                16            4
36       146562                                17            2
37       101003                                17            3
38       123926                                17            4
39       130927                                18            2
40       113972                                18            3
41       124300                                18            4
42       128440                                19            2
43       116183                                19            3
44       110768                                19            4

In [6]:
df = optimization_df[
    optimization_df["FinalProfit"] == optimization_df["FinalProfit"].max()
]
SDParameter = df["SDParameter"].unique()
IntervalForBounds = df["IntervalForBounds"].unique()
IntervalForRSV = df["IntervalForRSV"].unique()
FinalProfit = df["FinalProfit"].unique()

In [7]:
SDParameter

array([2], dtype=int64)

In [8]:
IntervalForBounds

array([15], dtype=int64)

In [9]:
IntervalForRSV

array([''], dtype=object)

In [10]:
FinalProfit

array([175860], dtype=int64)

In [2]:
%%time
from Grid_Tuning_geometric import grid_trading, speedy_grid_trading
FILENAME = "Decreasing_Data.csv"
data = pd.read_csv(FILENAME)
records_df, final_profit = speedy_grid_trading(
    data, INTERVAL_FOR_BOUNDS=15 * 24 * 60, SD_PARAMETER=2,
)
records_df["Hour"] = pd.to_datetime(records_df["Hour"])
records_df

IndexError: single positional indexer is out-of-bounds

In [9]:
import numpy as np

# records_df = records_df.sort_values(by="Hour", ascending=True)
records_df["TransactionInterval"] = records_df["Hour"].diff()
records_df = records_df.dropna()
records_df.loc[:, "TransactionInterval"] = records_df["TransactionInterval"].apply(
    lambda x: x.seconds
)
records_df

C:\Users\bizjun\Anaconda3\envs\AlgoTrading\lib\site-packages\pandas\core\indexing.py:1676: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)


Action  Price    n    Cash  Profit    LowerBound    UpperBound   Rate  \
1   Selling  58448  0.0  100440     440  52107.962513  60023.544671  0.006   
2    Buying  59056  1.0   41384  -58616  52107.952480  60023.858665  0.006   
3   Selling  59434  0.0  100818     818  52118.791899  60379.114287  0.006   
4    Buying  60090  1.0   40728  -59272  52118.759097  60379.582934  0.006   
5   Selling  60695  0.0  101423    1423  54322.625167  60744.777222  0.006   
6    Buying  60722  1.0   40701  -59299  54340.393522  60742.395282  0.006   
7   Selling  62377  0.0  103078    3078  55695.325335  62463.517689  0.006   
8    Buying  62561  1.0   40516  -59484  55642.790703  62607.168072  0.006   
9   Selling  62960  0.0  103477    3477  55547.776090  62963.954444  0.006   
10   Buying  63006  1.0   40471  -59529  55526.311871  63039.004301  0.006   
11   Buying  37315  2.0   25370  -74630  29307.694000  38943.652104  0.006   
12  Selling  37541  0.0  100451     451  29546.537897  37544.003689  0.006   
13   Buying  37590  2.0   25270  -74730  29525.753354  37608.349705  0.006   
14  Selling  37820  0.0  100910     910  29492.012487  37827.372318  0.006   
15   Buying  37853  2.0   25205  -74795  29489.905716  37866.632739  0.006   
16  Selling  38098  0.0  101401    1401  29507.209159  38104.056675  0.006   
17   Buying  39356  2.0   22690  -77310  29269.905411  39371.751444  0.006   
18  Selling  40169  0.0  103028    3028  29468.961212  40484.207446  0.006   
19   Buying  45567  2.0   11894  -88106  27852.503515  45620.678315  0.006   
20  Selling  45871  0.0  103635    3635  28185.491942  46793.260399  0.006   
21   Buying  46235  2.0   11164  -88836  28185.874401  46794.262191  0.006   
22  Selling  46518  0.0  104200    4200  28230.292823  46942.913085  0.006   
23   Buying  47513  2.0    9175  -90825  28402.109870  47518.711368  0.006   
24  Selling  47804  0.0  104782    4782  28510.176282  47833.698782  0.006   
25   Buying  47955  2.0    8873  -91127  28560.824490  47961.853194  0.006   
26  Selling  48314  0.0  105501    5501  29679.510389  50727.642706  0.006   
27   Buying  48931  2.0    7638  -92362  29679.974947  50728.584040  0.006   
28  Selling  49315  0.0  106268    6268  29844.058561  51098.610305  0.006   

                  Hour  TransactionInterval  
1  2021-03-30 17:43:00                63840  
2  2021-03-30 17:44:00                   60  
3  2021-03-31 14:52:00                76080  
4  2021-03-31 14:53:00                   60  
5  2021-10-04 12:21:00                77280  
6  2021-10-04 12:41:00                 1200  
7  2021-04-14 22:14:00                34380  
8  2021-04-15 01:59:00                13500  
9  2021-04-15 13:52:00                42780  
10 2021-04-15 16:17:00                 8700  
11 2021-01-29 23:59:00                27720  
12 2021-05-02 16:01:00                57720  
13 2021-05-02 17:57:00                 6960  
14 2021-05-02 23:53:00                21360  
15 2021-06-02 00:57:00                 3840  
16 2021-06-02 08:20:00                26580  
17 2021-07-02 07:40:00                84000  
18 2021-08-02 20:44:00                47040  
19 2021-10-02 20:37:00                85980  
20 2021-11-02 18:46:00                79740  
21 2021-11-02 18:47:00                   60  
22 2021-11-02 21:06:00                 8340  
23 2021-12-02 04:51:00                27900  
24 2021-12-02 09:22:00                16260  
25 2021-12-02 11:11:00                 6540  
26 2021-02-14 13:50:00                 9540  
27 2021-02-14 13:51:00                   60  
28 2021-02-14 20:13:00                22920

In [58]:
# records_df.to_excel("TransactionHistory_GeometricSequence.xlsx")