In [1]:
#%load_ext lab_black
#%config Completer.use_jedi = False
import pandas as pd
from Grid_Tuning import grid_trading, speedy_grid_trading
from tqdm import tqdm
import time

In [25]:
%%time

FILENAME = "Binance_BTC_1m.csv"
data = pd.read_csv(FILENAME)
optimization=[]
for interval_for_bounds in tqdm(range(5,20)):
    for sd in range(2,5):
        records_df, final_profit = speedy_grid_trading(
            data, INTERVAL_FOR_BOUNDS=interval_for_bounds * 24 * 60, SD_PARAMETER=sd,
        )
        optimization.append([final_profit, "", interval_for_bounds, sd])

100%|██████████████████████████████████████████████████████████████████████████████████| 15/15 [15:52<00:00, 63.49s/it]

Wall time: 15min 52s


In [3]:
# optimization=[]
# for interval_for_rsv in tqdm(range(10, 60)):
#     for interval_for_bounds in range(2, 20):
#         for sd_parameter in range(2,5):
#             records_df, final_profit = grid_trading(
#                 data, INTERVALS_FOR_RSV=interval_for_rsv, INTERVAL_FOR_BOUNDS=interval_for_bounds * 24 * 60, SD_PARAMETER=sd_parameter,
#             )
#             optimization.append([final_profit, interval_for_rsv, interval_for_bounds, sd_parameter])
#             print(time.ctime())

In [4]:
data

TimeStamp      Open      High       Low     Close  \
0       2020-11-19 01:23:00  17844.72  17878.78  17843.08  17864.41   
1       2020-11-19 01:24:00  17863.82  17864.32  17844.14  17844.73   
2       2020-11-19 01:25:00  17844.73  17849.41  17826.35  17828.35   
3       2020-11-19 01:26:00  17828.36  17829.99  17801.54  17803.66   
4       2020-11-19 01:27:00  17803.66  17806.29  17783.68  17799.98   
...                     ...       ...       ...       ...       ...   
199476  2021-04-06 22:38:00  57798.97  57831.81  57716.14  57758.10   
199477  2021-04-06 22:39:00  57758.09  57825.10  57745.28  57818.77   
199478  2021-04-06 22:40:00  57818.77  57860.83  57760.66  57783.63   
199479  2021-04-06 22:41:00  57783.62  57828.57  57760.00  57808.29   
199480  2021-04-06 22:42:00  57808.29  57808.30  57709.09  57777.17   

            Volume    boll_upper    boll_lower  
0       128.141795           NaN           NaN  
1        66.757429           NaN           NaN  
2        53.699989           NaN           NaN  
3       112.517483           NaN           NaN  
4        45.482920           NaN           NaN  
...            ...           ...           ...  
199476   94.209696  65518.712075  48442.012208  
199477   63.622250  65518.703989  48442.014190  
199478   96.278530  65518.689854  48442.017626  
199479   60.350468  65518.671377  48442.022544  
199480   94.035123  65518.653083  48442.027128  

[199481 rows x 8 columns]

In [26]:
optimization_df = pd.DataFrame(
    optimization,
    columns=["FinalProfit", "IntervalForRSV", "IntervalForBounds", "SDParameter",],
)

In [27]:
optimization_df.to_excel("Geometric_Sequence_Training_Parameters.xlsx")
# optimization_df = pd.read_excel("Training.xlsx")
optimization_df

FinalProfit IntervalForRSV  IntervalForBounds  SDParameter
0        104257                                 5            2
1         88510                                 5            3
2        106751                                 5            4
3        100238                                 6            2
4         82730                                 6            3
5        109663                                 6            4
6         97209                                 7            2
7         82225                                 7            3
8        107246                                 7            4
9        125369                                 8            2
10        98233                                 8            3
11       135331                                 8            4
12       155028                                 9            2
13       105916                                 9            3
14       144724                                 9            4
15       143293                                10            2
16       105590                                10            3
17       136303                                10            4
18       116148                                11            2
19       117229                                11            3
20       127345                                11            4
21       138484                                12            2
22       105887                                12            3
23       127066                                12            4
24       131189                                13            2
25       107272                                13            3
26       116401                                13            4
27       113831                                14            2
28       115085                                14            3
29       118958                                14            4
30       137534                                15            2
31       114892                                15            3
32       115392                                15            4
33       152179                                16            2
34       131317                                16            3
35       121166                                16            4
36       153821                                17            2
37       129404                                17            3
38       119249                                17            4
39       141333                                18            2
40       101260                                18            3
41       117556                                18            4
42       111454                                19            2
43       125215                                19            3
44       136369                                19            4

In [28]:
df = optimization_df[
    optimization_df["FinalProfit"] == optimization_df["FinalProfit"].max()
]
SDParameter = df["SDParameter"].unique()
IntervalForBounds = df["IntervalForBounds"].unique()
IntervalForRSV = df["IntervalForRSV"].unique()
FinalProfit = df["FinalProfit"].unique()

In [29]:
SDParameter

array([2], dtype=int64)

In [30]:
IntervalForBounds

array([9], dtype=int64)

In [31]:
IntervalForRSV

array([''], dtype=object)

In [32]:
FinalProfit

array([155028], dtype=int64)

In [33]:
from Grid_Tuning import grid_trading, speedy_grid_trading

records_df, final_profit = speedy_grid_trading(
    data, INTERVAL_FOR_BOUNDS=9 * 24 * 60, SD_PARAMETER=2,
)
records_df

Action  Price    n    Cash  Profit    LowerBound    UpperBound  \
0      Buying  18462  5.0    7689  -92311  17577.922116  19031.099631   
1     Selling  18611  0.0  100747     747  17801.509793  18973.826729   
2      Buying  18818  5.0    6657  -93343  17801.911725  18973.738783   
3     Selling  18971  0.0  101510    1510  17818.137869  18972.385303   
4      Buying  18971  5.0    6653  -93347  17823.545001  18972.165994   
...       ...    ...  ...     ...     ...           ...           ...   
5952  Selling  58533  0.0  243109  143109  45376.811729  59455.629676   
5953   Buying  59440  4.0    5349  -94651  45376.294776  59458.844849   
5954  Selling  60353  0.0  246760  146760  45335.550460  60411.732133   
5955   Buying  61048  4.0    2569  -97431  45387.961274  61050.984833   
5956  Selling  63115  0.0  255028  155028  55415.855339  63124.802751   

          Rate                 Hour  
0     0.005690  2020-11-24 01:22:00  
1     0.007112  2020-11-24 17:21:00  
2     0.007108  2020-11-24 17:22:00  
3     0.006999  2020-11-24 18:00:00  
4     0.006963  2020-11-24 18:12:00  
...        ...                  ...  
5952  0.014324      2021/3/13 18:12  
5953  0.014328      2021/3/13 18:14  
5954  0.015225       2021/3/14 3:37  
5955  0.015726       2021/3/14 9:21  
5956  0.006879      2021/4/14 17:24  

[5957 rows x 9 columns]

In [34]:
import numpy as np
temp=pd.to_datetime(records_df["Hour"])
# temp.diff()
records_df["TransactionInterval"]=temp.diff()
records_df

Action  Price    n    Cash  Profit    LowerBound    UpperBound  \
0      Buying  18462  5.0    7689  -92311  17577.922116  19031.099631   
1     Selling  18611  0.0  100747     747  17801.509793  18973.826729   
2      Buying  18818  5.0    6657  -93343  17801.911725  18973.738783   
3     Selling  18971  0.0  101510    1510  17818.137869  18972.385303   
4      Buying  18971  5.0    6653  -93347  17823.545001  18972.165994   
...       ...    ...  ...     ...     ...           ...           ...   
5952  Selling  58533  0.0  243109  143109  45376.811729  59455.629676   
5953   Buying  59440  4.0    5349  -94651  45376.294776  59458.844849   
5954  Selling  60353  0.0  246760  146760  45335.550460  60411.732133   
5955   Buying  61048  4.0    2569  -97431  45387.961274  61050.984833   
5956  Selling  63115  0.0  255028  155028  55415.855339  63124.802751   

          Rate                 Hour TransactionInterval  
0     0.005690  2020-11-24 01:22:00                 NaT  
1     0.007112  2020-11-24 17:21:00     0 days 15:59:00  
2     0.007108  2020-11-24 17:22:00     0 days 00:01:00  
3     0.006999  2020-11-24 18:00:00     0 days 00:38:00  
4     0.006963  2020-11-24 18:12:00     0 days 00:12:00  
...        ...                  ...                 ...  
5952  0.014324      2021/3/13 18:12    19 days 16:02:00  
5953  0.014328      2021/3/13 18:14     0 days 00:02:00  
5954  0.015225       2021/3/14 3:37     0 days 09:23:00  
5955  0.015726       2021/3/14 9:21     0 days 05:44:00  
5956  0.006879      2021/4/14 17:24    31 days 08:03:00  

[5957 rows x 10 columns]

In [35]:
records_df.to_excel("TransactionHistory_GeometricSequence.xlsx")