In [1]:
%load_ext lab_black
%config Completer.use_jedi = False
import pandas as pd
from Grid_Tuning_geometric import grid_trading, speedy_grid_trading
from tqdm import tqdm
import time

In [2]:
%%time

FILENAME = "Binance_BTC_1m.csv"
data = pd.read_csv(FILENAME)
optimization=[]
for interval_for_bounds in tqdm(range(5,20)):
    for sd in range(2,5):
        records_df, final_profit = speedy_grid_trading(
            data, INTERVAL_FOR_BOUNDS=interval_for_bounds * 24 * 60, SD_PARAMETER=sd,
        )
        optimization.append([final_profit, "", interval_for_bounds, sd])

100%|██████████████████████████████████████████████████████████████████████████████████| 15/15 [18:34<00:00, 74.33s/it]

Wall time: 18min 35s


In [3]:
# optimization=[]
# for interval_for_rsv in tqdm(range(10, 60)):
#     for interval_for_bounds in range(2, 20):
#         for sd_parameter in range(2,5):
#             records_df, final_profit = grid_trading(
#                 data, INTERVALS_FOR_RSV=interval_for_rsv, INTERVAL_FOR_BOUNDS=interval_for_bounds * 24 * 60, SD_PARAMETER=sd_parameter,
#             )
#             optimization.append([final_profit, interval_for_rsv, interval_for_bounds, sd_parameter])
#             print(time.ctime())

In [4]:
optimization_df = pd.DataFrame(
    optimization,
    columns=["FinalProfit", "IntervalForRSV", "IntervalForBounds", "SDParameter",],
)

In [5]:
# optimization_df.to_excel("Geometric_Sequence_Training_Parameters.xlsx")
# optimization_df = pd.read_excel("Training.xlsx")
optimization_df

FinalProfit IntervalForRSV  IntervalForBounds  SDParameter
0        146083                                 5            2
1        152521                                 5            3
2        113419                                 5            4
3        129581                                 6            2
4        120412                                 6            3
5        105766                                 6            4
6        134226                                 7            2
7        124318                                 7            3
8        111756                                 7            4
9        128901                                 8            2
10       111604                                 8            3
11       114050                                 8            4
12       134532                                 9            2
13       121695                                 9            3
14       120476                                 9            4
15       125333                                10            2
16       114289                                10            3
17       126836                                10            4
18       105352                                11            2
19       110367                                11            3
20       121966                                11            4
21        98945                                12            2
22       101481                                12            3
23       104411                                12            4
24       108350                                13            2
25       106021                                13            3
26       112721                                13            4
27       115603                                14            2
28       109425                                14            3
29       127460                                14            4
30       175860                                15            2
31       111953                                15            3
32       112201                                15            4
33       135392                                16            2
34        98963                                16            3
35       131530                                16            4
36       146562                                17            2
37       101003                                17            3
38       123926                                17            4
39       130927                                18            2
40       113972                                18            3
41       124300                                18            4
42       128440                                19            2
43       116183                                19            3
44       110768                                19            4

In [6]:
df = optimization_df[
    optimization_df["FinalProfit"] == optimization_df["FinalProfit"].max()
]
SDParameter = df["SDParameter"].unique()
IntervalForBounds = df["IntervalForBounds"].unique()
IntervalForRSV = df["IntervalForRSV"].unique()
FinalProfit = df["FinalProfit"].unique()

In [7]:
SDParameter

array([2], dtype=int64)

In [8]:
IntervalForBounds

array([15], dtype=int64)

In [9]:
IntervalForRSV

array([''], dtype=object)

In [10]:
FinalProfit

array([175860], dtype=int64)

In [3]:
data

Unnamed: 0  Unnamed: 0.1  Unnamed: 0.1.1        TimeStamp      Open  \
0            5000        125000          135620  2021/2/21 12:52  56530.69   
1            5001        125001          135621  2021/2/21 12:53  56526.38   
2            5002        125002          135622  2021/2/21 12:54  56550.00   
3            5003        125003          135623  2021/2/21 12:55  56604.55   
4            5004        125004          135624  2021/2/21 12:56  56572.71   
...           ...           ...             ...              ...       ...   
14995       19995        139995          113194   2021/2/5 21:47  37963.72   
14996       19996        139996          113195   2021/2/5 21:48  37978.08   
14997       19997        139997          113196   2021/2/5 21:49  38127.43   
14998       19998        139998          113197   2021/2/5 21:50  38172.02   
14999       19999        139999          113198   2021/2/5 21:51  38137.56   

           High       Low     Close      Volume  boll_upper  boll_lower  
0      56571.77  56523.90  56526.38   17.928238         NaN         NaN  
1      56590.00  56517.00  56550.01   25.635945         NaN         NaN  
2      56640.00  56542.94  56604.54   19.254883         NaN         NaN  
3      56613.83  56541.25  56569.16   18.708440         NaN         NaN  
4      56631.11  56544.52  56623.46   19.152437         NaN         NaN  
...         ...       ...       ...         ...         ...         ...  
14995  37999.68  37963.71  37978.09   89.867376         NaN         NaN  
14996  38130.17  37971.29  38130.00  178.493656         NaN         NaN  
14997  38198.78  38084.69  38172.03  211.731013         NaN         NaN  
14998  38172.03  38079.23  38140.94  158.094804         NaN         NaN  
14999  38141.20  38075.29  38110.48   92.377754         NaN         NaN  

[15000 rows x 11 columns]

In [2]:
%%time
from Grid_Tuning_geometric import grid_trading, speedy_grid_trading
import pandas as pd
FILENAME = "Decreasing_Data.csv"
data = pd.read_csv(FILENAME)
# interval_for_bounds=15*24*60
# sd_parameter=2
records_df, final_profit = speedy_grid_trading(
    data, INTERVAL_FOR_BOUNDS=15 * 24 * 60, SD_PARAMETER=2,
)
# print(records_df, final_profit)
records_df["Hour"] = pd.to_datetime(records_df["Hour"])
records_df

Wall time: 1.02 s


Action  Price    n    Cash  Profit    LowerBound    UpperBound   Rate  \
0   Buying  55970  1.0   44030  -55970  55489.056894  57840.795801  0.006   
1  Selling  56307  0.0  100338     338  55376.116986  57850.790764  0.006   
2   Buying  56823  1.0   43515  -56485  55376.999037  57850.717907  0.006   
3  Selling  57379  0.0  100894     894  54768.000487  57918.335430  0.006   

                 Hour  
0 2021-02-22 12:51:00  
1 2021-02-22 16:00:00  
2 2021-02-22 16:01:00  
3 2021-02-22 01:00:00

In [3]:
import numpy as np

# records_df = records_df.sort_values(by="Hour", ascending=True)
records_df["TransactionInterval"] = records_df["Hour"].diff()
records_df = records_df.dropna()
records_df.loc[:, "TransactionInterval"] = records_df["TransactionInterval"].apply(
    lambda x: x.seconds
)
records_df

C:\Users\bizjun\Anaconda3\envs\AlgoTrading\lib\site-packages\pandas\core\indexing.py:1676: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)


Action  Price    n    Cash  Profit    LowerBound    UpperBound   Rate  \
1  Selling  56307  0.0  100338     338  55376.116986  57850.790764  0.006   
2   Buying  56823  1.0   43515  -56485  55376.999037  57850.717907  0.006   
3  Selling  57379  0.0  100894     894  54768.000487  57918.335430  0.006   

                 Hour  TransactionInterval  
1 2021-02-22 16:00:00                11340  
2 2021-02-22 16:01:00                   60  
3 2021-02-22 01:00:00                32340

In [58]:
# records_df.to_excel("TransactionHistory_GeometricSequence.xlsx")