In [6]:
%load_ext lab_black
%config Completer.use_jedi = False
import pandas as pd
from Grid_Tuning_arithmetic_RSV import grid_trading, speedy_grid_trading
from tqdm import tqdm
import time

The lab_black extension is already loaded. To reload it, use:
  %reload_ext lab_black


In [7]:
# %%time

# FILENAME = "Binance_BTC_1m.csv"
# data = pd.read_csv(FILENAME)
# optimization_arithmetic=[]
# for interval_for_bounds in tqdm(range(5,20)):
#     for sd in range(2,5):
#         records_df, final_profit = speedy_grid_trading(
#             data, INTERVAL_FOR_BOUNDS=interval_for_bounds * 24 * 60, SD_PARAMETER=sd,
#         )
#         optimization_arithmetic.append([final_profit, "", interval_for_bounds, sd])

In [8]:
%%time
FILENAME = "Mild_Fluctuate_data.csv"
data = pd.read_csv(FILENAME)
optimization_RSV=[]
for interval_for_rsv in tqdm(range(10, 60,5)):
    for interval_for_bounds in range(5, 20,5):
        for sd_parameter in range(2,5):
            records_df, final_profit = grid_trading(
                data, INTERVALS_FOR_RSV=interval_for_rsv, INTERVAL_FOR_BOUNDS=interval_for_bounds * 24 * 60, SD_PARAMETER=sd_parameter,
            )
            optimization_RSV.append([final_profit, interval_for_rsv, interval_for_bounds, sd_parameter])
            print(time.ctime())

  0%|                                                                                           | 0/10 [00:00<?, ?it/s]

Mon May 10 15:25:57 2021
Mon May 10 15:26:02 2021
Mon May 10 15:26:06 2021
Mon May 10 15:26:10 2021
Mon May 10 15:26:14 2021
Mon May 10 15:26:18 2021
Mon May 10 15:26:21 2021
Mon May 10 15:26:25 2021


 10%|████████▎                                                                          | 1/10 [00:35<05:15, 35.07s/it]

Mon May 10 15:26:28 2021
Mon May 10 15:26:33 2021
Mon May 10 15:26:38 2021
Mon May 10 15:26:42 2021
Mon May 10 15:26:47 2021
Mon May 10 15:26:51 2021
Mon May 10 15:26:55 2021
Mon May 10 15:26:59 2021
Mon May 10 15:27:03 2021


 20%|████████████████▌                                                                  | 2/10 [01:13<04:54, 36.79s/it]

Mon May 10 15:27:06 2021
Mon May 10 15:27:11 2021
Mon May 10 15:27:16 2021
Mon May 10 15:27:21 2021
Mon May 10 15:27:25 2021
Mon May 10 15:27:29 2021
Mon May 10 15:27:33 2021
Mon May 10 15:27:37 2021
Mon May 10 15:27:40 2021


 30%|████████████████████████▉                                                          | 3/10 [01:49<04:17, 36.85s/it]

Mon May 10 15:27:43 2021
Mon May 10 15:27:49 2021
Mon May 10 15:27:53 2021
Mon May 10 15:27:57 2021
Mon May 10 15:28:02 2021
Mon May 10 15:28:06 2021
Mon May 10 15:28:10 2021
Mon May 10 15:28:13 2021
Mon May 10 15:28:17 2021


 40%|█████████████████████████████████▏                                                 | 4/10 [02:27<03:41, 36.99s/it]

Mon May 10 15:28:20 2021
Mon May 10 15:28:26 2021
Mon May 10 15:28:32 2021
Mon May 10 15:28:38 2021
Mon May 10 15:28:43 2021
Mon May 10 15:28:48 2021
Mon May 10 15:28:54 2021
Mon May 10 15:28:58 2021
Mon May 10 15:29:01 2021


 50%|█████████████████████████████████████████▌                                         | 5/10 [03:11<03:17, 39.48s/it]

Mon May 10 15:29:04 2021
Mon May 10 15:29:09 2021
Mon May 10 15:29:14 2021
Mon May 10 15:29:18 2021
Mon May 10 15:29:22 2021
Mon May 10 15:29:27 2021
Mon May 10 15:29:31 2021
Mon May 10 15:29:35 2021
Mon May 10 15:29:38 2021


 60%|█████████████████████████████████████████████████▊                                 | 6/10 [03:49<02:36, 39.24s/it]

Mon May 10 15:29:43 2021
Mon May 10 15:29:49 2021
Mon May 10 15:29:56 2021
Mon May 10 15:30:01 2021
Mon May 10 15:30:06 2021
Mon May 10 15:30:10 2021
Mon May 10 15:30:15 2021
Mon May 10 15:30:19 2021
Mon May 10 15:30:22 2021


 70%|██████████████████████████████████████████████████████████                         | 7/10 [04:33<02:01, 40.57s/it]

Mon May 10 15:30:26 2021
Mon May 10 15:30:32 2021
Mon May 10 15:30:36 2021
Mon May 10 15:30:42 2021
Mon May 10 15:30:47 2021
Mon May 10 15:30:51 2021
Mon May 10 15:30:56 2021
Mon May 10 15:31:00 2021
Mon May 10 15:31:04 2021


 80%|██████████████████████████████████████████████████████████████████▍                | 8/10 [05:13<01:21, 40.65s/it]

Mon May 10 15:31:07 2021
Mon May 10 15:31:12 2021
Mon May 10 15:31:18 2021
Mon May 10 15:31:22 2021
Mon May 10 15:31:26 2021
Mon May 10 15:31:30 2021
Mon May 10 15:31:34 2021
Mon May 10 15:31:38 2021
Mon May 10 15:31:42 2021


 90%|██████████████████████████████████████████████████████████████████████████▋        | 9/10 [05:53<00:40, 40.26s/it]

Mon May 10 15:31:47 2021
Mon May 10 15:31:53 2021
Mon May 10 15:31:58 2021
Mon May 10 15:32:05 2021
Mon May 10 15:32:10 2021
Mon May 10 15:32:15 2021
Mon May 10 15:32:19 2021
Mon May 10 15:32:23 2021
Mon May 10 15:32:27 2021


100%|██████████████████████████████████████████████████████████████████████████████████| 10/10 [06:38<00:00, 39.86s/it]

Mon May 10 15:32:32 2021
Wall time: 6min 38s


In [4]:
optimization_df = pd.DataFrame(
    optimization_RSV,
    columns=["FinalProfit", "IntervalForRSV", "IntervalForBounds", "SDParameter",],
)

In [11]:
# optimization_df.to_excel("Training_ArithmeticSequence_RSV.xlsx")
# optimization_df = pd.read_excel("Training.xlsx")
optimization_df

FinalProfit  IntervalForRSV  IntervalForBounds  SDParameter
0        140262              10                  5            2
1        160026              10                  5            3
2        108913              10                  5            4
3         99218              10                 10            2
4        107324              10                 10            3
..          ...             ...                ...          ...
85       134801              55                 10            3
86       150081              55                 10            4
87       185979              55                 15            2
88       128647              55                 15            3
89       128514              55                 15            4

[90 rows x 4 columns]

In [6]:
df = optimization_df[
    optimization_df["FinalProfit"] == optimization_df["FinalProfit"].max()
]
SDParameter = df["SDParameter"].unique()
IntervalForBounds = df["IntervalForBounds"].unique()
IntervalForRSV = df["IntervalForRSV"].unique()
FinalProfit = df["FinalProfit"].unique()

In [7]:
SDParameter

array([2], dtype=int64)

In [8]:
IntervalForBounds

array([15], dtype=int64)

In [9]:
IntervalForRSV

array([40], dtype=int64)

In [10]:
FinalProfit

array([199755], dtype=int64)

In [4]:
from Grid_Tuning_arithmetic_RSV import grid_trading

records_df, final_profit = grid_trading(
    data, INTERVALS_FOR_RSV=40, INTERVAL_FOR_BOUNDS=15 * 24 * 60, SD_PARAMETER=2,
)
records_df["Hour"] = pd.to_datetime(records_df["Hour"])
records_df

Action  Price    n    Cash  Profit    LowerBound    UpperBound  \
0   Buying  58008  1.0   41992  -58008  51953.683087  60367.202735   
1  Selling  58836  0.0  100828     828  52107.512470  60029.738970   
2   Buying  59434  1.0   41394  -58606  52107.462408  60030.118259   
3  Selling  60335  0.0  101729    1729  54321.763843  60744.828936   
4   Buying  60722  1.0   41007  -58993  54340.393522  60742.395282   
5  Selling  62377  0.0  103384    3384  55695.325335  62463.517689   
6   Buying  62561  1.0   40822  -59178  55642.790703  62607.168072   
7  Selling  62632  0.0  103455    3455  55594.792775  62793.838529   
8   Buying  62778  1.0   40677  -59323  55578.380604  62848.868137   
9  Selling  62830  0.0  103507    3507  55556.662502  62928.385632   

     LowerGrid    UpperGrid                Hour  
0   367.584004  1315.119925 2021-03-29 23:59:00  
1   792.222650   792.222650 2021-03-30 18:02:00  
2   792.265585   792.265585 2021-03-30 18:03:00  
3   642.306509   642.306509 2021-10-04 12:20:00  
4   458.419917   821.980435 2021-10-04 12:41:00  
5  1353.638471     0.000000 2021-04-14 22:14:00  
6  1392.875474     0.000000 2021-04-15 01:59:00  
7  1439.809151     0.000000 2021-04-15 08:37:00  
8  1454.097507     0.000000 2021-04-15 10:22:00  
9  1474.344626     0.000000 2021-04-15 12:45:00

In [5]:
import numpy as np

# records_df = records_df.sort_values(by="Hour", ascending=True)
records_df["TransactionInterval"] = records_df["Hour"].diff()
records_df = records_df.dropna()
records_df.loc[:, "TransactionInterval"] = records_df["TransactionInterval"].apply(
    lambda x: x.seconds
)
records_df

C:\Users\bizjun\Anaconda3\envs\AlgoTrading\lib\site-packages\pandas\core\indexing.py:1676: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)


Action  Price    n    Cash  Profit    LowerBound    UpperBound  \
1  Selling  58836  0.0  100828     828  52107.512470  60029.738970   
2   Buying  59434  1.0   41394  -58606  52107.462408  60030.118259   
3  Selling  60335  0.0  101729    1729  54321.763843  60744.828936   
4   Buying  60722  1.0   41007  -58993  54340.393522  60742.395282   
5  Selling  62377  0.0  103384    3384  55695.325335  62463.517689   
6   Buying  62561  1.0   40822  -59178  55642.790703  62607.168072   
7  Selling  62632  0.0  103455    3455  55594.792775  62793.838529   
8   Buying  62778  1.0   40677  -59323  55578.380604  62848.868137   
9  Selling  62830  0.0  103507    3507  55556.662502  62928.385632   

     LowerGrid   UpperGrid                Hour  TransactionInterval  
1   792.222650  792.222650 2021-03-30 18:02:00                64980  
2   792.265585  792.265585 2021-03-30 18:03:00                   60  
3   642.306509  642.306509 2021-10-04 12:20:00                65820  
4   458.419917  821.980435 2021-10-04 12:41:00                 1260  
5  1353.638471    0.000000 2021-04-14 22:14:00                34380  
6  1392.875474    0.000000 2021-04-15 01:59:00                13500  
7  1439.809151    0.000000 2021-04-15 08:37:00                23880  
8  1454.097507    0.000000 2021-04-15 10:22:00                 6300  
9  1474.344626    0.000000 2021-04-15 12:45:00                 8580

In [40]:
# records_df.to_excel("TransactionHistory_ArithmeticSequence.xlsx")